-- Up Migration

CREATE TABLE platform_metadata (key TEXT PRIMARY KEY, value TEXT NOT NULL);
INSERT INTO platform_metadata(key,value) VALUES ('stream_epoch','1'),('min_valid_position','0');
CREATE TABLE event_outbox (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, type TEXT NOT NULL, occurred_at TEXT NOT NULL,
 server_id TEXT NOT NULL, conversation_id TEXT, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL,
 recipient_user_ids TEXT NOT NULL, payload_entity_type TEXT NOT NULL, payload_entity_id TEXT NOT NULL
);
CREATE INDEX event_outbox_server_id_idx ON event_outbox(server_id,id);
CREATE TABLE consumer_positions (consumer TEXT PRIMARY KEY, position TEXT NOT NULL);

CREATE TABLE platform_jobs (
 id TEXT PRIMARY KEY,
 server_id TEXT NOT NULL,
 kind TEXT NOT NULL,
 payload_json TEXT NOT NULL,
 payload_hash TEXT NOT NULL,
 request_id TEXT,
 dedup_key TEXT,
 status TEXT NOT NULL CHECK(status IN ('pending','running','completed','failed')),
 attempt BIGINT NOT NULL DEFAULT 0 CHECK(attempt >= 0),
 next_run_at TEXT NOT NULL,
 lease_owner TEXT,
 lease_until TEXT,
 reason_code TEXT,
 created_at TEXT NOT NULL,
 updated_at TEXT NOT NULL,
 completed_at TEXT,
 CHECK ((status='running' AND lease_owner IS NOT NULL AND lease_until IS NOT NULL) OR (status<>'running' AND lease_owner IS NULL AND lease_until IS NULL)),
 UNIQUE(server_id,dedup_key)
);
CREATE INDEX platform_jobs_due_idx ON platform_jobs(status,next_run_at,created_at);
CREATE INDEX platform_jobs_lease_idx ON platform_jobs(status,lease_until);

CREATE TABLE mail_servers (id TEXT PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, server_id TEXT NOT NULL REFERENCES mail_servers(id),
 username TEXT NOT NULL, display_name TEXT NOT NULL, created_at TEXT NOT NULL,
 UNIQUE(server_id, username), UNIQUE(server_id, id)
);
CREATE TABLE sessions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, server_id TEXT NOT NULL, user_id BIGINT NOT NULL,
 token_hash TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, kind TEXT NOT NULL DEFAULT 'cookie',
 FOREIGN KEY(server_id,user_id) REFERENCES users(server_id,id)
);
CREATE INDEX sessions_expires_idx ON sessions(expires_at);
CREATE TABLE conversations (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, server_id TEXT NOT NULL REFERENCES mail_servers(id),
 kind TEXT NOT NULL CHECK(kind IN ('direct','group')), title TEXT, direct_pair TEXT,
 created_at TEXT NOT NULL, last_message_at TEXT,
 UNIQUE(server_id,id), UNIQUE(server_id,direct_pair)
);
CREATE TABLE members (
 server_id TEXT NOT NULL, conversation_id BIGINT NOT NULL, user_id BIGINT NOT NULL,
 PRIMARY KEY(server_id,conversation_id,user_id),
 FOREIGN KEY(server_id,conversation_id) REFERENCES conversations(server_id,id),
 FOREIGN KEY(server_id,user_id) REFERENCES users(server_id,id)
);
CREATE INDEX members_user_idx ON members(server_id,user_id,conversation_id);
CREATE TABLE conversation_requests (
 server_id TEXT NOT NULL, sender_id BIGINT NOT NULL, client_request_id TEXT NOT NULL,
 payload_digest TEXT NOT NULL, conversation_id BIGINT NOT NULL,
 PRIMARY KEY(server_id,sender_id,client_request_id),
 FOREIGN KEY(server_id,sender_id) REFERENCES users(server_id,id),
 FOREIGN KEY(server_id,conversation_id) REFERENCES conversations(server_id,id)
);
CREATE TABLE messages (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, server_id TEXT NOT NULL, conversation_id BIGINT NOT NULL,
 sender_id BIGINT NOT NULL, client_message_id TEXT NOT NULL, text TEXT, created_at TEXT NOT NULL,
 content_expired BIGINT NOT NULL DEFAULT 0 CHECK(content_expired IN (0,1)),
 CHECK((content_expired=0 AND text IS NOT NULL) OR (content_expired=1 AND text IS NULL)),
 UNIQUE(server_id,id), UNIQUE(server_id,sender_id,client_message_id),
 FOREIGN KEY(server_id,conversation_id) REFERENCES conversations(server_id,id),
 FOREIGN KEY(server_id,sender_id) REFERENCES users(server_id,id)
);
CREATE INDEX messages_conversation_id_idx ON messages(server_id,conversation_id,id);
CREATE INDEX messages_created_idx ON messages(server_id,created_at);
CREATE TABLE message_dedup (
 server_id TEXT NOT NULL, sender_id BIGINT NOT NULL, client_message_id TEXT NOT NULL,
 conversation_id BIGINT NOT NULL, message_id BIGINT, created_at TEXT NOT NULL, expired_at TEXT,
 PRIMARY KEY(server_id,sender_id,client_message_id),
 FOREIGN KEY(server_id,sender_id) REFERENCES users(server_id,id),
 FOREIGN KEY(server_id,conversation_id) REFERENCES conversations(server_id,id),
 FOREIGN KEY(server_id,message_id) REFERENCES messages(server_id,id)
);
CREATE TABLE message_files (
 server_id TEXT NOT NULL, message_id BIGINT NOT NULL, file_id TEXT NOT NULL,
 PRIMARY KEY(server_id,message_id,file_id), UNIQUE(server_id,file_id),
 FOREIGN KEY(server_id,message_id) REFERENCES messages(server_id,id)
);
CREATE TABLE read_cursors (
 server_id TEXT NOT NULL, conversation_id BIGINT NOT NULL, user_id BIGINT NOT NULL,
 last_read_message_id BIGINT NOT NULL, updated_at TEXT NOT NULL,
 PRIMARY KEY(server_id,conversation_id,user_id),
 FOREIGN KEY(server_id,conversation_id,user_id) REFERENCES members(server_id,conversation_id,user_id)
);
CREATE TABLE retention_policies (
 server_id TEXT PRIMARY KEY REFERENCES mail_servers(id), message_days BIGINT NOT NULL,
 file_days BIGINT NOT NULL, version BIGINT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE audit_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, server_id TEXT NOT NULL REFERENCES mail_servers(id),
 actor_id BIGINT, action TEXT NOT NULL, target_id TEXT, outcome TEXT NOT NULL,
 metadata_json TEXT NOT NULL, request_id TEXT NOT NULL, occurred_at TEXT NOT NULL,
 FOREIGN KEY(server_id,actor_id) REFERENCES users(server_id,id)
);
CREATE INDEX audit_server_id_idx ON audit_events(server_id,id);

CREATE TABLE files (
 id TEXT PRIMARY KEY, server_id TEXT NOT NULL, owner_user_id BIGINT NOT NULL,
 conversation_id BIGINT NOT NULL, filename TEXT, mime_type TEXT NOT NULL,
 size_bytes BIGINT NOT NULL CHECK(size_bytes>=0 AND size_bytes<=5000000),
 object_key TEXT NOT NULL UNIQUE, sha256 TEXT,
 state TEXT NOT NULL CHECK(state IN ('uploading','ready','attached','deleting','deleted')),
 created_at TEXT NOT NULL, expires_at TEXT NOT NULL, message_id BIGINT,
 delete_reason TEXT, deleted_at TEXT,
 FOREIGN KEY(server_id,owner_user_id) REFERENCES users(server_id,id),
 FOREIGN KEY(server_id,conversation_id) REFERENCES conversations(server_id,id)
);
CREATE INDEX files_expiry_idx ON files(server_id,state,expires_at);
CREATE INDEX files_conversation_idx ON files(server_id,conversation_id,created_at);
CREATE INDEX files_owner_idx ON files(server_id,owner_user_id,state);
CREATE INDEX files_message_idx ON files(server_id,message_id);
CREATE TABLE retention_progress (
 server_id TEXT NOT NULL REFERENCES mail_servers(id), kind TEXT NOT NULL,
 last_id TEXT, cutoff_at TEXT, policy_version BIGINT NOT NULL, updated_at TEXT NOT NULL,
 PRIMARY KEY(server_id,kind)
);

INSERT INTO platform_metadata(key,value) VALUES ('last_sequence','0');

-- Down Migration
DO $$ BEGIN RAISE EXCEPTION 'storage migration is forward-only; restore the verified backup'; END $$;
